builders:
  - script
triggers:
  cron: "@weekly"
slack:
  room: "eduid-builds"
pre_build_script:
  - "apt-get install -y libffi-dev"
script:
  - "python3.7 -m venv venv"
  - ". venv/bin/activate"
  - "pip install -U pip setuptools wheel mypy"
  - "pip install --index-url https://pypi.sunet.se -r test_requirements.txt"
  - "pip freeze"
  - "make test"
  - "make typecheck"
clean_workspace: true

extra_jobs:
  - name: sns-monitor-docker
    builders:
      - docker
    docker_name: sunet/sns-monitor
    triggers:
      github_push: false
      cron: null
    upstream:
      - eduid-docker-python3env
      - python-sns-monitor
